# Generated by Django 4.1.1 on 2022-09-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
        ),
    ]
